<?php

namespace Vesperia\TrainingBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Vesperia\TrainingBundle\DTO\SearchDTO;

/**
 * ConnectionLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectionLogRepository extends EntityRepository
{
    public function findBySearchDTO(SearchDTO $dto)
    {
        $queryBuilder = $this->createQueryBuilder('log');

        $queryBuilder->where('log.createdAt BETWEEN :startDate AND :endDate')
            ->setParameter('startDate', $dto->startDate)
            ->setParameter('endDate', $dto->endDate);
        
        if (!empty($dto->ipClient)) {
            $queryBuilder->andWhere('log.clientIp LIKE :client_ip')
                ->setParameter('client_ip', '%'.$dto->ipClient.'%');
        }
        
        return $queryBuilder->getQuery()->getResult();
    }
}
